# Go Log
#
# Copyright (c) 2023 Tvative
# All Rights Reserved
#
# Use of this source code is governed by
# certain licenses found in the LICENSE file

version: '3'

env:
  DIR_EXP: "Export/"
  DIR_TST: "Test/"

  LOG_TST: "{{.DIR_TST}}*.go"
  LOG_EXE: "{{.DIR_EXP}}Log"

tasks:
  CLEAN:
    desc: Clean Temporary Files / Directories
    platform:
      - linux/amd64
    cmds:
      - rm ${LOG_EXE}
      - rm ${DIR_TST}*.log

  MANUAL_TEST:
    desc: Unit Test Go Log Package
    platform:
      - linux/amd64
    cmds:
      - task: BUILD
      - ./${LOG_EXE}

  BUILD:
    desc: Build Go Log Package
    internal: true
    platform:
      - linux/amd64
    cmds:
      - go build -o ${LOG_EXE} ${LOG_TST}
